title: 我的博客
url: "https://xiaomao8.github.io"
baseurl: ""

remote_theme: mmistakes/minimal-mistakes@4.24.0

author: default

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

sass:
  style: compressed

# 默认 layout 设置
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      css: "/assets/css/custom.css"
      header:
        teaser: /assets/img/logo.png  # 默认 teaser，如果文章没设置

paginate: 5
paginate_path: "/page:num/"

# 导航菜单
navigation:
  main:
    - title: "首页"
      url: /
    - title: "文章分类"
      url: /categories/
    - title: "标签"
      url: /tags/
    - title: "关于"
      url: /about/



# ✅ 正确缩进的 collections
collections:
  pages:
    output: true










    






  
