title: 我的博客
url: "https://xiaomao8.github.io"
description: A minimal Jekyll blog with Minimal Mistakes
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge

permalink: /:categories/:title/